apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Pod
  patch: |-
    - op: replace
      path: /spec/containers/0/image
      value: wimvandenwyngaert/myalpine:1.0.2
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
