apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-version-checker
  labels:
    app: k8s-version-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-version-checker
  template:
    metadata:
      labels:
        app: k8s-version-checker
    spec:
      containers:
      - name: k8s-version-checker
        image: wimvandenwyngaert/k8s-version-checker:1.0.1
        env:
        - name: TZ
          value: Europe/Brussels
        command:
        - /bin/sh
        - -c
        - sleep infinity
