apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- echoserver.yaml
- ingress.yaml
- pod.yaml

labels:
- pairs:
    app.kubernetes.io/name: echoserver
    app.kubernetes.io/instance: echoserver-instance01
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: echoserver
  includeTemplates: true

buildMetadata: [managedByLabel]
