apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
  - name: alpine
    image: wimvandenwyngaert/test:2.3
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep infinity
    env:
    - name: TZ
      value: "Europe/Brussels"
    - name: ECHOSERVER_URL
      value: "http://echoserver-svc:80"
    resources:
      requests:
        memory: "1Gi"
        cpu: "5000m"
      limits:
        memory: "1Gi"
        cpu: "5"
