apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: wimvandenwyngaert/myalpine:1.0.2
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep 3600
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 100Mi
    env:
    - name: FIRST_NAME
      valueFrom:
        configMapKeyRef:
          key: first-name
          name: config
    - name: LAST_NAME
      valueFrom:
        configMapKeyRef:
          key: last-name
          name: config
