apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: wimvandenwyngaert/myalpine:1.0.0
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep 3600
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine2
spec:
  containers:
  - name: alpine
    image: wimvandenwyngaert/myalpine:1.0.0
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep 60
