apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: pod-reader-sax
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
