apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: pod-reader-sa
  namespace: test05
- kind: ServiceAccount
  name: pod-reader-sa
  namespace: test04
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
