apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  serviceAccountName: pod-reader-sa
  containers:
  - name: alpine
    image: wimvandenwyngaert/myalpine:1.0.2
    command:
    - /bin/sh
    - -c
    - sleep infinity
