apiVersion: v1
kind: Pod
metadata:
  name: test-pod-for-pvc
  labels:
    app: test-pod-for-pvc
spec:
  containers:
  - name: alpine
    image: wimvandenwyngaert/test:2.3
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep infinity
    env:
    - name: TZ
      value: "Europe/Brussels"
