---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  application.namespaces: "test-apps, simple-apps"
