apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  application.namespaces: "core-apps, test-apps, simple-apps"
  server.insecure: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add local user "wim" with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to log in using UI
  accounts.wim: "apiKey, login"
  kustomize.buildOptions: "--enable-helm"
  exec.enabled: "true"
  statusbadge.enabled: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: ''
  policy.csv: |
    p, role:test-role, applications, get, */*, allow
    p, role:test-role, projects, get, *, allow
    g, wim, role:test-role
