apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: ''
  policy.csv: |
    p, role:test-role, applications, get, */*, allow
    p, role:test-role, projects, get, *, allow

    g, wim, role:test-role
