apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.1/manifests/install.yaml
- ingress.yaml
- argocdapp.yaml

patches:
- path: configmaps.yaml
- patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - argoproj.io
        resources:
        - applications
        - applicationsets
        - appprojects
        verbs:
        - create
        - get
        - list
        - watch
        - update
        - delete
        - patch
  target:
    kind: ClusterRole
    name: argocd-server
