apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink | quote }}
  food: {{ .Values.favoriteFood | quote }}
  car: {{ .Values.favoriteCar | quote }}
