apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
  - name: "{{ .Values.containerName}}"
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep 3600
    env:
    - name: CHART_NAME
      valueFrom:
        configMapKeyRef:
          name: {{ .Chart.Name }}-configmap-2
          key: chartName
    - name: CHART_VERSION
      valueFrom:
        configMapKeyRef:
          name: {{ .Chart.Name }}-configmap-2
          key: chartVersion
    - name: CHART_DESCRIPTION
      valueFrom:
        configMapKeyRef:
          name: {{ .Chart.Name }}-configmap-2
          key: chartDescription
