apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  version: 4.0.18
  releaseName: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
  valuesInline:
    nfs:
      server: 192.168.1.5
      path: /mnt/nfsshare
    storageClass:
      reclaimPolicy: Retain

namespace: nfs-provisioner
