apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-dep
  labels:
    app: echo-dep
spec:
  selector:
    matchLabels:
      run: my-echo-server
  replicas: 1
  template:
    metadata:
      labels:
        run: my-echo-server
    spec:
      containers:
      - name: echo-server
        image: ealen/echo-server:0.9.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 100Mi
