apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'simple-app-dev'
    name: 'in-cluster'
  - namespace: 'simple-app-prd'
    name: 'in-cluster'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: my-project
  source:
    repoURL: https://github.com/wim-vdw/kubernetes-tests.git
    targetRevision: HEAD
    path: argocd/simple-app/overlays/dev
  destination:
    name: in-cluster
    namespace: simple-app-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-prd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: my-project
  source:
    repoURL: https://github.com/wim-vdw/kubernetes-tests.git
    targetRevision: HEAD
    path: argocd/simple-app/overlays/prd
  destination:
    name: in-cluster
    namespace: simple-app-prd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
