apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  labels:
    env: production
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/wim-vdw/kubernetes-tests.git
    targetRevision: main
    path: argocd/root-app-manifests
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
