apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: AppProject
  patch: |-
    - op: replace
      path: /metadata/name
      value: simple-app
    - op: replace
      path: /spec/description
      value: Project for simple application
    - op: add
      path: /spec/sourceNamespaces
      value: [simple-apps"]
