apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test04-production
spec:
  ingressClassName: nginx
  rules:
  - host: blue-green-prd.192.168.1.11.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blue-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test04-blue
spec:
  ingressClassName: nginx
  rules:
  - host: blue-app.192.168.1.11.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blue-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test04-green
spec:
  ingressClassName: nginx
  rules:
  - host: green-app.192.168.1.11.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: green-svc
            port:
              number: 80
