apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- blue-app.yaml
- green-app.yaml
- ingress.yaml

labels:
- pairs:
    app.kubernetes.io/name: blue-green
    app.kubernetes.io/instance: blue-green-instance01
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: blue-green
    app.kubernetes.io/managed-by: ArgoCD
