apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- projects/overlays/simple-app
- projects/overlays/tests
- apps/overlays/test01
- apps/overlays/test02
- apps/overlays/test03
- apps/overlays/test04
- apps/overlays/simple-app/dev
- apps/overlays/simple-app/acc
- apps/overlays/simple-app/prd
