apiVersion: v1
kind: Namespace
metadata:
  name: test02
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test02
spec:
  volumes:
  - name: data
    hostPath:
      path: /data
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    imagePullPolicy: IfNotPresent
    workingDir: /usr/share/nginx/html
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
