apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    environment: development
spec:
  volumes:
  - name: data
    hostPath:
      path: /data
  containers:
  - name: nginx
    image: nginx:1.27.2-alpine
    imagePullPolicy: IfNotPresent
    workingDir: /usr/share/nginx/html
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
  - name: alpine
    image: wimvandenwyngaert/test:2.3
    command:
    - /bin/sh
    - -c
    - sleep infinity
    volumeMounts:
    - mountPath: /data
      name: data
