apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/pv01
  capacity:
    storage: 1Gi
  claimRef:
    name: pvc-static-01
    namespace: test06
