apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-0001
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeName: pv0001
  resources:
    requests:
      storage: 1Gi
