apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-dep
  annotations:
    configmap.reloader.stakater.com/reload: {{ .Chart.Name }}-configmap-2
spec:
  selector:
    matchLabels:
      app: helm-test
  template:
    metadata:
      labels:
        app: helm-test
    spec:
      containers:
      - name: "{{ .Values.containerName}}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - sh
        - -c
        - echo 'Welcome Wim' && sleep infinity
        env:
        - name: CHART_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-configmap-2
              key: chartName
        - name: CHART_VERSION
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-configmap-2
              key: chartVersion
        - name: CHART_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-configmap-2
              key: chartAppVersion
        - name: CHART_DESCRIPTION
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-configmap-2
              key: chartDescription
        - name: RELOADER_TEST
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-configmap-2
              key: reloaderTest
