apiVersion: v1
kind: Namespace
metadata:
  name: test03
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test03
  labels:
    app: test-pod
spec:
  containers:
  - name: alpine
    image: wimvandenwyngaert/myalpine:1.0.2
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep 3600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-dep
  namespace: test03
  labels:
    app: echo-dep
spec:
  selector:
    matchLabels:
      run: my-echo-server
  replicas: 3
  template:
    metadata:
      labels:
        run: my-echo-server
    spec:
      containers:
      - name: echo-server
        image: ealen/echo-server:0.8.12
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  namespace: test03
  labels:
    app: echo-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-echo-server
