apiVersion: v1
kind: Namespace
metadata:
  name: test03
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test03
  labels:
    app: test-pod
spec:
  containers:
  - name: alpine
    image: wimvandenwyngaert/myalpine:1.0.1
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && sleep 3600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: test03
  labels:
    app: nginx-dep
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 3
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: test03
  labels:
    run: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
