apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  labels:
    env: production
  namespace: test-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: tests
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13
    helm:
      releaseName: external-secrets
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
