apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project3
  namespace: argocd
spec:
  description: Test project 3
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
