apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

patches:
- target:
    kind: Application
  patch: |-
    - op: replace
      path: /metadata/name
      value: simple-app-acc
    - op: replace
      path: /metadata/labels/env
      value: acceptance
    - op: replace
      path: /spec/project
      value: simple-app
    - op: replace
      path: /spec/source/path
      value: simple-app/overlays/acc
    - op: replace
      path: /spec/destination/namespace
      value: simple-app-acc
