apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
  namespace: test01
  labels:
    app: echo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:1.0.0
        args:
        - "-text=Hello Wim"
        ports:
        - containerPort: 5678
