apiVersion: v1
kind: Pod
metadata:
  name: readiness-test
  labels:
    test: readiness
spec:
  containers:
  - name: readiness
    image: wimvandenwyngaert/myalpine:1.0.2
    args:
    - /bin/sh
    - -c
    - sleep 15; touch /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
