apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: test01
data:
  number_of_processes: "3"
  file.properties: |
    processes=3
    application=test
    port=8080
    debug=FALSE
---
apiVersion: v1
kind: Secret
metadata:
  name: user-data
data:
  username: V2ltIFZhbiBkZW4gV3luYWdlcnQK
  password: cGFzczEyMwo=
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test01
  labels:
    app: nginx-po
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx-testapp
    app.kubernetes.io/component: webserver
    app.kubernetes.io/version: 1.0.0
spec:
  containers:
  - name: nginx
    image: nginx:1.25.3-alpine
    imagePullPolicy: IfNotPresent
    workingDir: /config
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 100Mi
    env:
    - name: TIER
      value: frontend
    - name: ENVIRONMENT
      value: development
    - name: NUMBER_OF_PROCESSES
      valueFrom:
        configMapKeyRef:
          key: number_of_processes
          name: nginx
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: user-data
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: user-data
          key: password
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: nginx
      items:
      - key: "file.properties"
        path: "config.txt"
