apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test01
  labels:
    app: nginx-po
spec:
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    imagePullPolicy: IfNotPresent
    workingDir: /var/log/nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 100Mi
    env:
    - name: TIER
      value: frontend
    - name: ENVIRONMENT
      value: development
