apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: test01
data:
  number_of_processes: "3"
  file.properties: |
    processes=3
    application=test
    port=8080
    debug=FALSE
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test01
  labels:
    app: nginx-po
spec:
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    imagePullPolicy: IfNotPresent
    workingDir: /config
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 100Mi
    env:
    - name: TIER
      value: frontend
    - name: ENVIRONMENT
      value: development
    - name: NUMBER_OF_PROCESSES
      valueFrom:
        configMapKeyRef:
          key: number_of_processes
          name: nginx
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: nginx
      items:
      - key: "file.properties"
        path: "config.txt"
