apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helmcharts

helmCharts:
- name: simplechart
  valuesInline:
    favoriteDrink: wine
    containerName: alpine-container
    image:
      tag: "1.0.2"
  additionalValuesFiles:
  - values-file-1.yaml
