apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helmcharts

helmCharts:
- name: mychart
  valuesInline:
    containerName: alpine-container
    image:
      tag: "1.0.2"
